export const ROUTES = {
  HOME: '/',
  CATALOG: '/catalog',
  PROFILE: {
    ROOT: '/profile',
    CHILDREN: {
      INDEX: '',
      REQUESTS: 'requests',
      EXCHANGES: 'exchanges',
      FAVORITES: 'favorites',
      SKILLS: 'skills',
    },
  },
  CREATE: '/create',
  LOGIN: '/login',
  REGISTER: '/register',
  REGISTER_STEP_TWO: '/register/step-2',
  ABOUT: '/about',
  CONTACTS: '/contacts',
  BLOG: '/blog',
  SKILL_DETAILS: '/skills/:authorId',
  POLICY: '/policy',
  TERMS: '/terms',
  NOTFOUND: '*',
  SERVER_ERROR: '/500',
} as const;
